FROM golang

WORKDIR /gen

COPY gen/main.go .

RUN go mod init github.com/headblockhead/pheonix

RUN go mod tidy

COPY gen .

ENV SEED="128"

RUN go build -o /usr/bin/phoenix

WORKDIR /phoenix_images

CMD phoenix